### ISSUE TITLE
Read up on storage methods for simple Java applications

### ISSUE THREAD

**Issue by anaprimawaty** [cs2103aug2015-w14-2j/main#20]

**Comment by hackkillers** [comment]
http://stackoverflow.com/questions/15154049/xml-vs-json-which-one-is-better-for-storing-small-chunk-of-data

**Comment by anaprimawaty** [comment]
Researched on XML and JSON.

Tried to implement JSON storage using Gson library but faced difficulties in storing abstract classes.

Decided on regular text file for storage at this point in time. Will work on alternatives in future iterations if this does not suffice.
