### ISSUE TITLE
Data support for DateTime from Java library

### ISSUE THREAD

**Issue by hackkillers** [cs2103aug2015-w14-2j/main#28]

**Comment by qianpeisheng** [comment]
https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html

**Comment by hackkillers** [comment]
Decided to use LocalDateTIme API
https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html

**Comment by hackkillers** [comment]
Implemented in DeadlineTask.java and BoundedTask.java
