### ISSUE TITLE
Logic support for help command

### ISSUE THREAD

**Issue by hackkillers** [cs2103aug2015-w14-2j/main#86]
Need suggestions on what content to include

**Comment by qianpeisheng** [comment]
for the help output object: the return message will not be displayed, but will be used to check if it is a help object (currently it is placeholder, pls inform me after update); in the task array list, pls follow the format
[
["help message 1",,...],
["help message 2",,...],
...
["last help message",,...]
]
meaning the first element of each array list inside is the message, and rest are empty string

**Comment by hackkillers** [comment]
passed to UI
